// Curated cross-section of common UK garden plant genera, grouped by the
// categories named in the brief (trees, shrubs, perennials, climbers, bulbs,
// hanging-basket/bedding) — per SPEC-001's requirement to seed a defensible
// cross-section rather than randomly sampling RHS's ~306k plant pages.
export const GENUS_CATEGORIES: Record<string, string[]> = {
  trees: [
    "acer",
    "betula",
    "prunus",
    "malus",
    "sorbus",
    "quercus",
    "fagus",
    "crataegus",
    "tilia",
    "carpinus",
    "ilex",
    "magnolia",
    "salix",
    "robinia",
    "liquidambar",
  ],
  shrubs: [
    "rosa",
    "hydrangea",
    "buddleja",
    "viburnum",
    "camellia",
    "rhododendron",
    "hebe",
    "buxus",
    "philadelphus",
    "forsythia",
    "weigela",
    "choisya",
    "ceanothus",
    "potentilla",
    "spiraea",
    "skimmia",
    "mahonia",
    "pittosporum",
  ],
  perennials: [
    "geranium",
    "salvia",
    "achillea",
    "echinacea",
    "hylotelephium",
    "lupinus",
    "delphinium",
    "campanula",
    "digitalis",
    "verbena",
    "nepeta",
    "alchemilla",
    "astilbe",
    "heuchera",
    "bergenia",
    "euphorbia",
    "helleborus",
    "symphyotrichum",
    "hosta",
    "iris",
  ],
  climbers: [
    "clematis",
    "hedera",
    "wisteria",
    "jasminum",
    "lonicera",
    "passiflora",
    "humulus",
    "akebia",
    "campsis",
    "trachelospermum",
  ],
  bulbs: [
    "tulipa",
    "narcissus",
    "allium",
    "crocus",
    "galanthus",
    "hyacinthus",
    "muscari",
    "dahlia",
    "gladiolus",
    "fritillaria",
    "colchicum",
  ],
  hangingBasketBedding: [
    "pelargonium",
    "petunia",
    "lobelia",
    "begonia",
    "fuchsia",
    "bacopa",
    "calibrachoa",
    "viola",
    "bidens",
    "nemesia",
    "diascia",
  ],
};

export function allGenera(): string[] {
  const set = new Set<string>();
  for (const genera of Object.values(GENUS_CATEGORIES)) {
    for (const g of genera) set.add(g);
  }
  return [...set];
}
